// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back. Useful for verifying MCP connectivity.",
  inputSchema: {
    text: z.string().min(1).describe("Text to echo back.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/app-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
var app_info_default = defineTool2({
  name: "app_info",
  title: "App info",
  description: "Return basic information about this church management app.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify({
          name: "\uC2E0\uD48D \uC640\uB4DC \uAD50\uD68C \uAD00\uB9AC (Sinpung Ward Church Manager)",
          description: "\uAD50\uD68C \uD68C\uC6D0 \uAE30\uB85D, \uCD9C\uC11D, \uC131\uCC2C\uC2DD \uC21C\uC11C, \uC870\uC9C1\uB3C4, \uD68C\uC758\uB85D, \uCCAD\uC18C\uC870, \uC131\uC804 \uCD94\uCC9C\uC11C\uB97C \uAD00\uB9AC\uD558\uB294 \uC571\uC785\uB2C8\uB2E4.",
          features: [
            "\uD68C\uC6D0 \uAE30\uB85D (Members)",
            "\uCD9C\uC11D\uBD80 (Attendance)",
            "\uCD9C\uC11D \uD1B5\uACC4 (Attendance stats)",
            "\uC131\uCC2C\uC2DD \uC21C\uC11C (Sacrament order)",
            "\uC870\uC9C1\uB3C4 (Org chart)",
            "\uD68C\uC758\uB85D (Meeting minutes)",
            "\uCCAD\uC18C\uC870 (Cleaning teams)",
            "\uC131\uC804 \uCD94\uCC9C\uC11C (Temple recommends)"
          ]
        })
      }
    ]
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "sinpung-ward-mcp",
  title: "\uC2E0\uD48D \uC640\uB4DC \uAD50\uD68C \uAD00\uB9AC MCP",
  version: "0.1.0",
  instructions: "\uC2E0\uD48D \uC640\uB4DC \uAD50\uD68C \uAD00\uB9AC \uC571\uC758 \uACF5\uAC1C MCP \uC11C\uBC84\uC785\uB2C8\uB2E4. `echo`\uB85C \uC5F0\uACB0\uC744 \uD655\uC778\uD558\uACE0, `app_info`\uB85C \uC571 \uC815\uBCF4\uB97C \uC870\uD68C\uD558\uC138\uC694. \uC774 \uC11C\uBC84\uB294 \uC778\uC99D \uC5C6\uC774 \uACF5\uAC1C\uC801\uC73C\uB85C \uC811\uADFC \uAC00\uB2A5\uD558\uBA70, \uD68C\uC6D0/\uCD9C\uC11D \uB4F1 \uAC1C\uC778 \uB370\uC774\uD130\uB294 \uB178\uCD9C\uD558\uC9C0 \uC54A\uC2B5\uB2C8\uB2E4.",
  tools: [echo_default, app_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
