// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvjnitjudzmqtgzxbchb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2am5pdGp1ZHptcXRnenhiY2hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU4ODM0MTQsImV4cCI6MjEwMTQ1OTQxNH0.iD81uLKbP1pYJVKQWx9z4SeiQwRPnlODZGjprHKeztA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});